<script type="text/javascript" language="javascript" class="init">
	$(document).ready(function() {
		
	} );

	<?php echo $this->view->js;?>
</script>
<style >
    .cdonuts{
  height:400px;
}
</style>
<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
echo $this->view->botones;
echo $this->view->tabla;
?>
<h3>&Oacute;rdenes de los &uacute;ltimos 7 d&iacute;as</h3>
<div id="ordenSemana" class="cdonuts"></div>
<script type="text/javascript" language="javascript">

var chart = new Morris.Donut({
  // ID of the element in which to draw the chart.
  element: 'ordenSemana',
  // Chart data records -- each entry in this array corresponds to a point on
  // the chart.
  data: [
    { label: 'Hamburguesas', value: 0 },
    { label: 'Papas_fritas', value: 0 }
  ],
  // The name of the data record attribute that contains x-values.
  //xkey: 'semana',
  // A list of names of data record attributes that contain y-values.
  //ykeys: ['h', 'p'],
  // Labels for the ykeys -- will be displayed when you hover over the
  // chart.
  //labels: ['h', 'p']
}, 2000);    
/*var data = [
    { semana: '2010', a: 5, b: 10 },
    { year: '2011', a: 5, b: 15 },
    { year: '2012', a: 20, b: 5 }
];
chart.setData(data);
*/
// Create a function that will handle AJAX requests
  function requestData(days, chart, cname){
      //chart.empty();
    $.ajax({
      type: "POST",
      dataType: 'json',
      url: "reporte/chartData", // This is the URL to the API
      data: { days: days, cname: cname}
    })
    .done(function( data ) {
      // When the response to the AJAX request comes back render the chart with new data
      chart.setData(data);
      //chart.setLabels([]);
    })
    .fail(function() {
      // If there is no communication between the server, show an error
      alert( "error occured" );
    });
  }
  
  requestData(7, chart, "ordenSemana");
</script>
    