<script type="text/javascript" language="javascript" class="init">
	$(document).ready(function() {
            requestData(1, chart, "ordenSemana");
            var counter = 10;
            var timer = function(){
                if(counter < 1){
                    var d = $("#hdias").val();
                    requestData(d, chart, "ordenSemana");
                    counter = 11;
                }
                      counter--;
                      setTimeout(timer,1000);
                    };
            timer();
	} );

	<?php echo $this->view->js;?>
</script>
<style >
    .cdonuts{
  height:400px;
}
div{
    align: center;
}
</style>
<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
echo $this->view->botones;
echo $this->view->tabla;
?>
<div class="btn-group" role="group" aria-label="...">
    <button type="button" class="btn btn-default" onclick="muestraDona(1);">Hoy</button>
  <button type="button" class="btn btn-default" onclick="muestraDona(7);">7 D&iacute;as</button>
  <button type="button" class="btn btn-default" onclick="muestraDona(15);">15 D&iacute;as</button>
  <button type="button" class="btn btn-default" onclick="muestraDona(30);">30 D&iacute;as</button>
</div>
<div id="tDonut"><h3>&Oacute;rdenes de los &uacute;ltimos 1 d&iacute;as</h3></div>
<div id="ordenSemana" class="cdonuts"></div>
<script type="text/javascript" language="javascript">

function muestraDona(dias){
    $("#tDonut").html("<h3>&Oacute;rdenes de los &uacute;ltimos " + dias + " d&iacute;as</h3>");
    $("#hdias").val(dias);
    requestData(dias, chart, "ordenSemana");
}

var chart = new Morris.Donut({
  element: 'ordenSemana',
  data: [
    { label: 'Hamburguesas', value: 0 },
    { label: 'Papas_fritas', value: 0 }
  ],
}, 2000);    
  function requestData(days, chart, cname){
    $.ajax({
      type: "POST",
      dataType: 'json',
      url: "reporte/chartData", // This is the URL to the API
      data: { days: days, cname: cname}
    })
    .done(function( data ) {
      // When the response to the AJAX request comes back render the chart with new data
      chart.setData(data);      
    })
    .fail(function() {
      // If there is no communication between the server, show an error
      alert( "error occured" );
    });
  }
  
  
</script>
    