<script type="text/javascript">
    ion.sound({
                sounds: [
                    {
                        name: "bikeHorn"
                    }
                ],
                volume: 1.0,
                path: "sounds/",
                preload: true
            });
            
	$(document).ready(function() {
            listar();
            var counter = 10;
            var timer = function(){
                if(counter < 1){
                    tabla.ajax.reload( null, false );
                    totales();
                    counter = 11;
                }
                      counter--;
                      setTimeout(timer,1000);
                    };
            timer();
            
            var totales = function(){
                $.ajax({
			type: "POST",
			url: "orden/totalesCocina", 
                        data: {cid: $('#lid').val()}, 
			dataType: "json",
			success: function(result){
				var jsondata = jQuery.parseJSON(JSON.stringify(result)); 
				$("#totalesDiv").html(jsondata.tots);
                                $("#lid").val(jsondata.lid);
                                if(jsondata.nt > 0){
                                   for (i = 0; i < jsondata.nt; i++) {
                                       ion.sound.play("bikeHorn");
                                   }
                                }
			}});
            };
            
            
            /*
            $('#dept').change(function() {
		var dis = 0;
		var $radios = $('input:radio[value=Departamento]');
		if($radios.is(':checked') === true) {
			dis = 1;
		}
		$.ajax({
			type: "POST",
			url: "formulario/listUsers", 
			data: {dept: $('#dept').val(), disable: dis},
			dataType: "json",
			success: function(result){
				var jsondata = jQuery.parseJSON(JSON.stringify(result)); 
				$("#udiv").html(jsondata.select);
			}});
            });*/
            
	} );
        var tabla = "";
        var listar = function (){
            tabla = $('#tordenes').DataTable({
                        //"processing": false,
                        //"serverSide": true,
			//"aaSorting": [[ 0, "desc" ], [1, "asc"]],
                        "ajax": {
                            "url": "orden/tablaCocina",
                            "type": "POST"
			},
                        "columns": [
                            { "data": "p" },
                            { "data": "n" },
                            { "data": "o" },
                            { "data": "c" },
                            { "data": "e" }
                        ]
		});
            };         
</script>
<link rel="stylesheet" type="text/css" href="css/cocina.css">
<?php 
echo $this->view->titulo;
echo $this->getContent(); 
echo $this->tag->hiddenField ( array ("lid", "value" => "") );
?>
<div id="totalesDiv">
<?php
echo $this->view->form; 
//echo $this->view->tabla;
?>
</div>
<div id="counter" name="counter" class="counter"></div>
<table id="tordenes" class="display" cellspacing="0" width="95%">
    <thead>
        <tr>
            <th>P</th>
            <th>N&uacute;mero</th>
            <th>Orden</th>
            <th>Cambios</th>
            <th>Estado</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>P</th>
            <th>N&uacute;mero</th>
            <th>Orden</th>
            <th>Cambios</th>
            <th>Estado</th>
        </tr>
    </tfoot>
</table>