<script type="text/javascript">
    var pause = false;
    
	function addHidden(id){
		var tot = parseInt($("#n"+id).val());
		tot = tot + 1;
		$("#n"+id).val(tot);
		$("#d"+id).val(tot); 
	};

	function remHidden(id){
		var tot = parseInt($("#n"+id).val());
		if(tot <= 0){
			tot = 0;
		}else{
			tot = tot - 1;
		}
		$("#n"+id).val(tot);
		$("#d"+id).val(tot); 
	};

	$(document).ready(function() {
		/*$('#torden').DataTable({
			"aaSorting": [[ 0, "desc" ]]
			});*/
            listar();
            var counter = 10;
            var timer = function(){
                if(counter < 1){
                    tabla.ajax.reload( null, false );
                    counter = 11;
                }
                      counter--;
                      setTimeout(timer,1000);
                    };
            timer();
            $('#plus').hide();
            $('.edit').hide();

		/*var counter = 60;
		var timer = function(){
			$('div.counter').html("La p&aacute;gina se recargar&aacute; en " +counter + " segundos");
			  if(counter == 0){
				  //alert("termino counter");
				  this.document.location.href = "/cafeteria/orden";
			  }
                          if(pause == false){
                            counter--;			      
                          }
			  setTimeout(timer,1000);
			};
		timer();*/	
	} );
        /*
        function pauseCounter(){
            pause = true;
            $('div.b_pause').html("<span class=\"glyphicon glyphicon-play\" onclick=\"playCounter();\">");
        }
        
        function playCounter(){
            pause = false;
            $('div.b_pause').html("<span class=\"glyphicon glyphicon-pause\" onclick=\"pauseCounter();\">");
        }
*/
	function hideForm() {
		$("#hform").hide();
		$("#plus").show();
	}

	function showForm() {
		$("#plus").hide();
		$("#hform").show();
	}
        
        function fillMenu(ids) {
            var spl = ids.split(";");
            $.each(spl, function(index, value){
               var items = value.split(",");
               $("#nx" + items[0]).val(items[1]);
               $("#d" + items[0]).val(items[1]);
            });
               
        }
        
        var tabla = "";
        var listar = function (){
            tabla = $('#torden').DataTable({
                        "aaSorting": [[ 0, "desc" ]],// [1, "asc"]],
                        "ajax": {
                            "url": "orden/tablaOrden",
                            "type": "POST"
			},
                        "columns": [
                            { "data": "p" },
                            { "data": "n" },
                            { "data": "o" },
                            { "data": "h" },
                            { "data": "c" },
                            { "data": "e" },
                            { "data": "a" }
                        ] 
		});
            };
            
            <?php echo $this->view->js;?>
</script>
<link rel="stylesheet" type="text/css" href="css/orden.css">
<?php 
echo $this->view->titulo;
echo $this->getContent(); 
?>
<div id="hform" class="hform">
<?php 
echo $this->view->form;
echo $this->view->botones;
//echo $this->view->tabla;
/*
<div id="counter" name="counter" class="counter"></div>
<div id="b_pause" name="b_pause" class="b_pause"><span class="glyphicon glyphicon-pause" onclick="pauseCounter();"></span></div>
 */

?>
<a onClick ="hideForm();" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-chevron-up" ></span></a>
</div>
<div id="plus">
<a onClick ="showForm();" class="btn btn-info btn-lg"><span class="glyphicon glyphicon-chevron-down"></span></a>
</div>
<div id="tdiv" class='col-sm-12'>
<table id="torden" class="display" cellspacing="0" width="95%">
    <thead>
        <tr>
            <th>P</th>
            <th>N&uacute;mero</th>
            <th>Orden</th>
            <th>Hora</th>
            <th>Cambios</th>
            <th>Estado</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>P</th>
            <th>N&uacute;mero</th>
            <th>Orden</th>
            <th>Hora</th>
            <th>Cambios</th>
            <th>Estado</th>
            <th>Acciones</th>
        </tr>
    </tfoot>
</table>
</div>
